#datasource
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  profiles:
    active: test
#mybatis
mybatis:
  type-aliases-package: com.dj.springboot.pojo
  mapper-locations: classpath:mapper/*.xml